server {
    listen 80;
    server_name xn----8sbgjrbcagaihxeflmw5fye5a.xn--p1ai;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name xn----8sbgjrbcagaihxeflmw5fye5a.xn--p1ai;

    ssl_certificate /etc/letsencrypt/live/xn----8sbgjrbcagaihxeflmw5fye5a.xn--p1ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xn----8sbgjrbcagaihxeflmw5fye5a.xn--p1ai/privkey.pem;

    root /usr/share/nginx/landing-html;
    index index.html;

    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_comp_level 6;
    gzip_types application/javascript application/json image/svg+xml text/css text/plain;

    location = / {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        index index.html;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files /index.html =404;
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location / {
        try_files $uri =404;
    }
}
